package com.lingoflow.app.ui.theme

import androidx.compose.ui.graphics.Color

// ---------------------------------------------------------------------------
// MODERN (blue) — dark
// ---------------------------------------------------------------------------
val LingoFlowPrimary = Color(0xFF5E9CFF)
val LingoFlowOnPrimary = Color(0xFF0B0F17)
val LingoFlowPrimaryContainer = Color(0xFF234A80)
val LingoFlowOnPrimaryContainer = Color(0xFFD6E4FF)
val LingoFlowSecondary = Color(0xFF00BCD4)
val LingoFlowOnSecondary = Color(0xFF0B0F17)
val LingoFlowSecondaryContainer = Color(0xFF0E4A54)
val LingoFlowOnSecondaryContainer = Color(0xFFB8F1FA)
val LingoFlowTertiary = Color(0xFF9BB4D4)
val LingoFlowOnTertiary = Color(0xFF0B0F17)
val LingoFlowTertiaryContainer = Color(0xFF334B66)
val LingoFlowOnTertiaryContainer = Color(0xFFDCE8F7)
val LingoFlowBackground = Color(0xFF0B0F17)
val LingoFlowSurface = Color(0xFF151C28)
val LingoFlowSurfaceElevated = Color(0xFF1E2634)
val LingoFlowSurfaceLowest = Color(0xFF0F141E)
val LingoFlowSurfaceLow = Color(0xFF121823)
val LingoFlowSurfaceHigh = Color(0xFF232C3C)
val LingoFlowSurfaceHighest = Color(0xFF2A3446)
val LingoFlowOnSurface = Color(0xFFF3F6FB)
val LingoFlowOnSurfaceVariant = Color(0xFF98A2B3)
/** Hairline card border on dark surfaces (shadows are invisible in dark UI). */
val LingoFlowOutlineDark = Color(0x14FFFFFF)
val LingoFlowOutlineVariantDark = Color(0xFF2A3446)
val LingoFlowInverseSurfaceDark = Color(0xFFF3F6FB)
val LingoFlowInverseOnSurfaceDark = Color(0xFF1A2230)
val LingoFlowInversePrimaryDark = Color(0xFF3373C4)
val LingoFlowErrorDark = Color(0xFFF2B8B5)
val LingoFlowOnErrorDark = Color(0xFF601410)
val LingoFlowErrorContainerDark = Color(0xFF8C1D18)
val LingoFlowOnErrorContainerDark = Color(0xFFF9DEDC)

// ---------------------------------------------------------------------------
// MODERN (blue) — light
// ---------------------------------------------------------------------------
val LingoFlowPrimaryLight = Color(0xFF3373C4)
val LingoFlowOnPrimaryLight = Color(0xFFFFFFFF)
val LingoFlowPrimaryContainerLight = Color(0xFFD6E3FA)
val LingoFlowOnPrimaryContainerLight = Color(0xFF0A3059)
val LingoFlowSecondaryLight = Color(0xFF0090A8)
val LingoFlowOnSecondaryLight = Color(0xFFFFFFFF)
val LingoFlowSecondaryContainerLight = Color(0xFFC5F1FA)
val LingoFlowOnSecondaryContainerLight = Color(0xFF083A44)
val LingoFlowTertiaryLight = Color(0xFF4C6E9E)
val LingoFlowOnTertiaryLight = Color(0xFFFFFFFF)
val LingoFlowTertiaryContainerLight = Color(0xFFD8E4F7)
val LingoFlowOnTertiaryContainerLight = Color(0xFF1E3A5F)
val LingoFlowLightBackground = Color(0xFFF6F7F9)
val LingoFlowLightSurface = Color(0xFFFFFFFF)
val LingoFlowLightSurfaceElevated = Color(0xFFFFFFFF)
val LingoFlowLightSurfaceLowest = Color(0xFFF3F4F6)
val LingoFlowLightSurfaceHigh = Color(0xFFFFFFFF)
val LingoFlowLightSurfaceHighest = Color(0xFFF0F2F5)
val LingoFlowLightOnSurface = Color(0xFF151A22)
val LingoFlowLightOnSurfaceVariant = Color(0xFF64707F)
/** Hairline card border on light surfaces. */
val LingoFlowOutlineLight = Color(0xFFE6E9EE)
val LingoFlowOutlineVariantLight = Color(0xFFD9DEE6)
val LingoFlowInverseSurfaceLight = Color(0xFF2A303B)
val LingoFlowInverseOnSurfaceLight = Color(0xFFF1F3F7)
val LingoFlowInversePrimaryLight = Color(0xFFA0C9FF)
val LingoFlowErrorLight = Color(0xFFBA1A1A)
val LingoFlowOnErrorLight = Color(0xFFFFFFFF)
val LingoFlowErrorContainerLight = Color(0xFFFFDAD6)
val LingoFlowOnErrorContainerLight = Color(0xFF410002)

// ---------------------------------------------------------------------------
// EDITORIAL (warm paper) — light
// Primary is a darkened terracotta (#C96F4A → #AD5533): white text on the
// original hue measured ~3.5:1, below the WCAG AA 4.5:1 for chip/button
// labels; the darkened hue clears it.
// ---------------------------------------------------------------------------
val EditorialLightPrimary = Color(0xFFAD5533)
val EditorialLightOnPrimary = Color(0xFFFFFFFF)
val EditorialLightPrimaryContainer = Color(0xFFFBDBCB)
val EditorialLightOnPrimaryContainer = Color(0xFF3A1405)
val EditorialLightSecondary = Color(0xFF8C7355)
val EditorialLightOnSecondary = Color(0xFFFFFFFF)
val EditorialLightSecondaryContainer = Color(0xFFF0E0CB)
val EditorialLightOnSecondaryContainer = Color(0xFF332615)
val EditorialLightTertiary = Color(0xFF6E6046)
val EditorialLightOnTertiary = Color(0xFFFFFFFF)
val EditorialLightTertiaryContainer = Color(0xFFF2E9D5)
val EditorialLightOnTertiaryContainer = Color(0xFF241F10)
val EditorialLightBackground = Color(0xFFFAF6EF)
val EditorialLightSurface = Color(0xFFFFFDF8)
val EditorialLightElevated = Color(0xFFFFFFFF)
val EditorialLightSurfaceLowest = Color(0xFFF5F0E7)
val EditorialLightSurfaceHigh = Color(0xFFFFFFFF)
val EditorialLightSurfaceHighest = Color(0xFFF1EBDF)
val EditorialLightOnSurface = Color(0xFF2A2620)
val EditorialLightOnSurfaceVariant = Color(0xFF6E655A)
val EditorialLightOutline = Color(0xFFE7DFD3)
val EditorialLightOutlineVariant = Color(0xFFD6CCBB)
val EditorialLightInverseSurface = Color(0xFF3A352D)
val EditorialLightInverseOnSurface = Color(0xFFF5F0E7)
val EditorialLightInversePrimary = Color(0xFFFFB693)
val EditorialLightError = Color(0xFFBA1A1A)
val EditorialLightOnError = Color(0xFFFFFFFF)
val EditorialLightErrorContainer = Color(0xFFFFDAD6)
val EditorialLightOnErrorContainer = Color(0xFF410002)

// ---------------------------------------------------------------------------
// EDITORIAL (warm paper) — dark (night reading)
// ---------------------------------------------------------------------------
val EditorialDarkPrimary = Color(0xFFD98E6A)
val EditorialDarkOnPrimary = Color(0xFF16120D)
val EditorialDarkPrimaryContainer = Color(0xFF5C2E17)
val EditorialDarkOnPrimaryContainer = Color(0xFFFFDBC7)
val EditorialDarkSecondary = Color(0xFFB09A7D)
val EditorialDarkOnSecondary = Color(0xFF16120D)
val EditorialDarkSecondaryContainer = Color(0xFF3F3428)
val EditorialDarkOnSecondaryContainer = Color(0xFFE6D4BC)
val EditorialDarkTertiary = Color(0xFFB3A37F)
val EditorialDarkOnTertiary = Color(0xFF16120D)
val EditorialDarkTertiaryContainer = Color(0xFF403827)
val EditorialDarkOnTertiaryContainer = Color(0xFFEADFC6)
val EditorialDarkBackground = Color(0xFF16120D)
val EditorialDarkSurface = Color(0xFF211C15)
val EditorialDarkElevated = Color(0xFF2A241B)
val EditorialDarkSurfaceLowest = Color(0xFF1B1610)
val EditorialDarkSurfaceLow = Color(0xFF1F1A13)
val EditorialDarkSurfaceHigh = Color(0xFF2A241B)
val EditorialDarkSurfaceHighest = Color(0xFF322B20)
val EditorialDarkOnSurface = Color(0xFFEFE7DA)
val EditorialDarkOnSurfaceVariant = Color(0xFFA79B8A)
val EditorialDarkOutline = Color(0x24EFE7DA)
val EditorialDarkOutlineVariant = Color(0xFF4A4234)
val EditorialDarkInverseSurface = Color(0xFFEFE7DA)
val EditorialDarkInverseOnSurface = Color(0xFF211C15)
val EditorialDarkInversePrimary = Color(0xFFA65B37)
val EditorialDarkError = Color(0xFFF2B8B5)
val EditorialDarkOnError = Color(0xFF601410)
val EditorialDarkErrorContainer = Color(0xFF8C1D18)
val EditorialDarkOnErrorContainer = Color(0xFFF9DEDC)
